# Copyright Contributors to the Open Cluster Management project

language: node_js
node_js: '12'
install: npm ci --no-optional
addons:
    sonarcloud:
        organization: 'open-cluster-management'
jobs:
    include:
        - stage: Pull Request
          if: type = pull_request
          script:
              - npm test &&
                npm run lint &&
                npm run check &&
                npm run build &&
                npm run build:storybook

        - stage: Build and Publish
          if: type = push AND branch = main
          script:
              - npm test &&
                npm run build &&
                npm run build:storybook &&
                scripts/publish.sh &&
                sonar-scanner
          deploy:
              provider: pages
              skip_cleanup: true
              github_token: $GITHUB_TOKEN
              keep_history: true
              local_dir: storybook-static
              on:
                  branch: main

        - stage: Automated Dependency Upgrade
          if: type = cron AND branch = main
          install: echo skip install
          script: scripts/update.sh
